In [42]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [95]:
df=pd.read_csv(r"HR_attrition.csv")

In [112]:
df=pd.read_csv("HR_attrition.csv")
df['salary'].replace(to_replace=['medium'],value='high',inplace=True)
    


df.loc[df.salary=='medium','left']='0'
df.loc[df.salary=='high','left']='0'
df.salary.replace(to_replace=['medium'],value='high')

0         low
1        high
2        high
3         low
4         low
5         low
6         low
7         low
8         low
9         low
10        low
11        low
12        low
13        low
14        low
15        low
16        low
17        low
18        low
19        low
20        low
21        low
22        low
23        low
24        low
25        low
26        low
27        low
28        low
29        low
         ... 
14969    high
14970    high
14971    high
14972    high
14973    high
14974    high
14975    high
14976    high
14977    high
14978    high
14979    high
14980    high
14981     low
14982    high
14983    high
14984    high
14985    high
14986     low
14987     low
14988     low
14989     low
14990     low
14991     low
14992     low
14993     low
14994     low
14995     low
14996     low
14997     low
14998     low
Name: salary, Length: 14999, dtype: object

In [114]:
df

left  satisfaction_level  last_evaluation  number_project  \
0        1                0.38             0.53               2   
1        0                0.80             0.86               5   
2        0                0.11             0.88               7   
3        1                0.72             0.87               5   
4        1                0.37             0.52               2   
5        1                0.41             0.50               2   
6        1                0.10             0.77               6   
7        1                0.92             0.85               5   
8        1                0.89             1.00               5   
9        1                0.42             0.53               2   
10       1                0.45             0.54               2   
11       1                0.11             0.81               6   
12       1                0.84             0.92               4   
13       1                0.41             0.55               2   
14       1                0.36             0.56               2   
15       1                0.38             0.54               2   
16       1                0.45             0.47               2   
17       1                0.78             0.99               4   
18       1                0.45             0.51               2   
19       1                0.76             0.89               5   
20       1                0.11             0.83               6   
21       1                0.38             0.55               2   
22       1                0.09             0.95               6   
23       1                0.46             0.57               2   
24       1                0.40             0.53               2   
25       1                0.89             0.92               5   
26       1                0.82             0.87               4   
27       1                0.40             0.49               2   
28       1                0.41             0.46               2   
29       1                0.38             0.50               2   
...    ...                 ...              ...             ...   
14969    0                0.43             0.46               2   
14970    0                0.78             0.93               4   
14971    0                0.39             0.45               2   
14972    0                0.11             0.97               6   
14973    0                0.36             0.52               2   
14974    0                0.36             0.54               2   
14975    0                0.10             0.79               7   
14976    0                0.40             0.47               2   
14977    0                0.81             0.85               4   
14978    0                0.40             0.47               2   
14979    0                0.09             0.93               6   
14980    0                0.76             0.89               5   
14981    1                0.73             0.93               5   
14982    0                0.38             0.49               2   
14983    0                0.72             0.84               5   
14984    0                0.40             0.56               2   
14985    0                0.91             0.99               5   
14986    1                0.85             0.85               4   
14987    1                0.90             0.70               5   
14988    1                0.46             0.55               2   
14989    1                0.43             0.57               2   
14990    1                0.89             0.88               5   
14991    1                0.09             0.81               6   
14992    1                0.40             0.48               2   
14993    1                0.76             0.83               6   
14994    1                0.40             0.57               2   
14995    1                0.37             0.48               2   
14996    1                0.37             0.53      

In [115]:
type(df)

pandas.core.frame.DataFrame

In [116]:
df.head(100)

left  satisfaction_level  last_evaluation  number_project  \
0     1                0.38             0.53               2   
1     0                0.80             0.86               5   
2     0                0.11             0.88               7   
3     1                0.72             0.87               5   
4     1                0.37             0.52               2   
5     1                0.41             0.50               2   
6     1                0.10             0.77               6   
7     1                0.92             0.85               5   
8     1                0.89             1.00               5   
9     1                0.42             0.53               2   
10    1                0.45             0.54               2   
11    1                0.11             0.81               6   
12    1                0.84             0.92               4   
13    1                0.41             0.55               2   
14    1                0.36             0.56               2   
15    1                0.38             0.54               2   
16    1                0.45             0.47               2   
17    1                0.78             0.99               4   
18    1                0.45             0.51               2   
19    1                0.76             0.89               5   
20    1                0.11             0.83               6   
21    1                0.38             0.55               2   
22    1                0.09             0.95               6   
23    1                0.46             0.57               2   
24    1                0.40             0.53               2   
25    1                0.89             0.92               5   
26    1                0.82             0.87               4   
27    1                0.40             0.49               2   
28    1                0.41             0.46               2   
29    1                0.38             0.50               2   
..  ...                 ...              ...             ...   
70    0                0.74             0.99               2   
71    0                0.09             0.77               5   
72    0                0.45             0.49               2   
73    1                0.09             0.87               7   
74    0                0.11             0.97               6   
75    0                0.11             0.79               7   
76    0                0.10             0.83               6   
77    0                0.40             0.54               2   
78    1                0.43             0.56               2   
79    1                0.39             0.56               2   
80    1                0.45             0.54               2   
81    1                0.38             0.49               2   
82    1                0.79             0.59               4   
83    1                0.84             0.85               4   
84    1                0.11             0.77               6   
85    1                0.11             0.87               6   
86    1                0.17             0.84               5   
87    1                0.44             0.45               2   
88    1                0.37             0.57               2   
89    1                0.10             0.79               6   
90    1                0.40             0.50               2   
91    1                0.89             1.00               5   
92    1                0.42             0.48               2   
93    1                0.46             0.55               2   
94    1                0.09             0.83               6   
95    1                0.37             0.51               2   
96    1                0.10             0.77               6   
97    1                0.10             0.84               6   
98    1                0.11             0.97               6   
99    0                0.90             1.00               5   

    average_montly_hours  time_spe

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
left                     14999 non-null object
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
promotion_last_5years    14999 non-null int64
salary                   14999 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 1.0+ MB


In [118]:
df.mean()

satisfaction_level         0.612834
last_evaluation            0.716102
number_project             3.803054
average_montly_hours     201.050337
time_spend_company         3.498233
Work_accident              0.144610
promotion_last_5years      0.021268
dtype: float64

In [119]:
df.fillna(dataset.mean(),inplace=True)

In [120]:
df

left  satisfaction_level  last_evaluation  number_project  \
0        1                0.38             0.53               2   
1        0                0.80             0.86               5   
2        0                0.11             0.88               7   
3        1                0.72             0.87               5   
4        1                0.37             0.52               2   
5        1                0.41             0.50               2   
6        1                0.10             0.77               6   
7        1                0.92             0.85               5   
8        1                0.89             1.00               5   
9        1                0.42             0.53               2   
10       1                0.45             0.54               2   
11       1                0.11             0.81               6   
12       1                0.84             0.92               4   
13       1                0.41             0.55               2   
14       1                0.36             0.56               2   
15       1                0.38             0.54               2   
16       1                0.45             0.47               2   
17       1                0.78             0.99               4   
18       1                0.45             0.51               2   
19       1                0.76             0.89               5   
20       1                0.11             0.83               6   
21       1                0.38             0.55               2   
22       1                0.09             0.95               6   
23       1                0.46             0.57               2   
24       1                0.40             0.53               2   
25       1                0.89             0.92               5   
26       1                0.82             0.87               4   
27       1                0.40             0.49               2   
28       1                0.41             0.46               2   
29       1                0.38             0.50               2   
...    ...                 ...              ...             ...   
14969    0                0.43             0.46               2   
14970    0                0.78             0.93               4   
14971    0                0.39             0.45               2   
14972    0                0.11             0.97               6   
14973    0                0.36             0.52               2   
14974    0                0.36             0.54               2   
14975    0                0.10             0.79               7   
14976    0                0.40             0.47               2   
14977    0                0.81             0.85               4   
14978    0                0.40             0.47               2   
14979    0                0.09             0.93               6   
14980    0                0.76             0.89               5   
14981    1                0.73             0.93               5   
14982    0                0.38             0.49               2   
14983    0                0.72             0.84               5   
14984    0                0.40             0.56               2   
14985    0                0.91             0.99               5   
14986    1                0.85             0.85               4   
14987    1                0.90             0.70               5   
14988    1                0.46             0.55               2   
14989    1                0.43             0.57               2   
14990    1                0.89             0.88               5   
14991    1                0.09             0.81               6   
14992    1                0.40             0.48               2   
14993    1                0.76             0.83               6   
14994    1                0.40             0.57               2   
14995    1                0.37             0.48               2   
14996    1                0.37             0.53      

In [121]:
df.head(100)

left  satisfaction_level  last_evaluation  number_project  \
0     1                0.38             0.53               2   
1     0                0.80             0.86               5   
2     0                0.11             0.88               7   
3     1                0.72             0.87               5   
4     1                0.37             0.52               2   
5     1                0.41             0.50               2   
6     1                0.10             0.77               6   
7     1                0.92             0.85               5   
8     1                0.89             1.00               5   
9     1                0.42             0.53               2   
10    1                0.45             0.54               2   
11    1                0.11             0.81               6   
12    1                0.84             0.92               4   
13    1                0.41             0.55               2   
14    1                0.36             0.56               2   
15    1                0.38             0.54               2   
16    1                0.45             0.47               2   
17    1                0.78             0.99               4   
18    1                0.45             0.51               2   
19    1                0.76             0.89               5   
20    1                0.11             0.83               6   
21    1                0.38             0.55               2   
22    1                0.09             0.95               6   
23    1                0.46             0.57               2   
24    1                0.40             0.53               2   
25    1                0.89             0.92               5   
26    1                0.82             0.87               4   
27    1                0.40             0.49               2   
28    1                0.41             0.46               2   
29    1                0.38             0.50               2   
..  ...                 ...              ...             ...   
70    0                0.74             0.99               2   
71    0                0.09             0.77               5   
72    0                0.45             0.49               2   
73    1                0.09             0.87               7   
74    0                0.11             0.97               6   
75    0                0.11             0.79               7   
76    0                0.10             0.83               6   
77    0                0.40             0.54               2   
78    1                0.43             0.56               2   
79    1                0.39             0.56               2   
80    1                0.45             0.54               2   
81    1                0.38             0.49               2   
82    1                0.79             0.59               4   
83    1                0.84             0.85               4   
84    1                0.11             0.77               6   
85    1                0.11             0.87               6   
86    1                0.17             0.84               5   
87    1                0.44             0.45               2   
88    1                0.37             0.57               2   
89    1                0.10             0.79               6   
90    1                0.40             0.50               2   
91    1                0.89             1.00               5   
92    1                0.42             0.48               2   
93    1                0.46             0.55               2   
94    1                0.09             0.83               6   
95    1                0.37             0.51               2   
96    1                0.10             0.77               6   
97    1                0.10             0.84               6   
98    1                0.11             0.97               6   
99    0                0.90             1.00               5   

    average_montly_hours  time_spe

In [122]:
#separating dependent and independent variables
x=df.iloc[:,0:2].values

In [123]:
x#dependent variables

array([[1, 0.38],
       ['0', 0.8],
       ['0', 0.11],
       ...,
       [1, 0.37],
       [1, 0.11],
       [1, 0.37]], dtype=object)

In [124]:
y=df.iloc[:,4:7].values

In [125]:
y#dependent variables

array([[157,   3,   0],
       [262,   6,   0],
       [272,   4,   0],
       ...,
       [143,   3,   0],
       [280,   4,   0],
       [158,   3,   0]])

In [126]:
z=df.iloc[:,7:9].values

In [127]:
z#dependent variables

array([[0, 'low'],
       [0, 'high'],
       [0, 'high'],
       ...,
       [0, 'low'],
       [0, 'low'],
       [0, 'low']], dtype=object)

In [128]:
m=df.iloc[:,2:4].values

m

In [129]:
m#independent variables

array([[0.53, 2.  ],
       [0.86, 5.  ],
       [0.88, 7.  ],
       ...,
       [0.53, 2.  ],
       [0.96, 6.  ],
       [0.52, 2.  ]])

In [130]:
n=df.iloc[:,6]

In [131]:
n#independent variables

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       1
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
14969    0
14970    0
14971    0
14972    0
14973    0
14974    0
14975    0
14976    0
14977    0
14978    0
14979    0
14980    0
14981    0
14982    0
14983    0
14984    0
14985    0
14986    0
14987    0
14988    0
14989    1
14990    1
14991    0
14992    0
14993    0
14994    0
14995    0
14996    0
14997    0
14998    0
Name: Work_accident, Length: 14999, dtype: int64

In [132]:
df.shape

(14999, 9)

In [133]:
df.index

RangeIndex(start=0, stop=14999, step=1)

In [134]:
df.columns

Index(['left', 'satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'salary'],
      dtype='object')

In [135]:
#separating categorical data and numerical data

In [136]:
df.head(10)

left  satisfaction_level  last_evaluation  number_project  \
0    1                0.38             0.53               2   
1    0                0.80             0.86               5   
2    0                0.11             0.88               7   
3    1                0.72             0.87               5   
4    1                0.37             0.52               2   
5    1                0.41             0.50               2   
6    1                0.10             0.77               6   
7    1                0.92             0.85               5   
8    1                0.89             1.00               5   
9    1                0.42             0.53               2   

   average_montly_hours  time_spend_company  Work_accident  \
0                   157                   3              0   
1                   262                   6              0   
2                   272                   4              0   
3                   223                   5              0   
4                   159                   3              0   
5                   153                   3              0   
6                   247                   4              0   
7                   259                   5              0   
8                   224                   5              0   
9                   142                   3              0   

   promotion_last_5years salary  
0                      0    low  
1                      0   high  
2                      0   high  
3                      0    low  
4                      0    low  
5                      0    low  
6                      0    low  
7                      0    low  
8                      0    low  
9                      0    low

In [145]:
from sklearn.preprocessing import LabelEncoder

In [146]:
lb=LabelEncoder()

In [147]:
x[:,1]=lb.fit_transform(x[:,1])

In [148]:
x

array([[1, 29],
       ['0', 71],
       ['0', 2],
       ...,
       [1, 28],
       [1, 2],
       [1, 28]], dtype=object)

In [149]:

y=df.iloc[:,8].values

In [150]:
y

array(['low', 'high', 'high', ..., 'low', 'low', 'low'], dtype=object)

In [151]:
lb_y=LabelEncoder()

In [152]:
y=lb_y.fit_transform(y)

In [160]:


y

array([1, 0, 0, ..., 1, 1, 1])

In [161]:
df

left  satisfaction_level  last_evaluation  number_project  \
0        1                0.38             0.53               2   
1        0                0.80             0.86               5   
2        0                0.11             0.88               7   
3        1                0.72             0.87               5   
4        1                0.37             0.52               2   
5        1                0.41             0.50               2   
6        1                0.10             0.77               6   
7        1                0.92             0.85               5   
8        1                0.89             1.00               5   
9        1                0.42             0.53               2   
10       1                0.45             0.54               2   
11       1                0.11             0.81               6   
12       1                0.84             0.92               4   
13       1                0.41             0.55               2   
14       1                0.36             0.56               2   
15       1                0.38             0.54               2   
16       1                0.45             0.47               2   
17       1                0.78             0.99               4   
18       1                0.45             0.51               2   
19       1                0.76             0.89               5   
20       1                0.11             0.83               6   
21       1                0.38             0.55               2   
22       1                0.09             0.95               6   
23       1                0.46             0.57               2   
24       1                0.40             0.53               2   
25       1                0.89             0.92               5   
26       1                0.82             0.87               4   
27       1                0.40             0.49               2   
28       1                0.41             0.46               2   
29       1                0.38             0.50               2   
...    ...                 ...              ...             ...   
14969    0                0.43             0.46               2   
14970    0                0.78             0.93               4   
14971    0                0.39             0.45               2   
14972    0                0.11             0.97               6   
14973    0                0.36             0.52               2   
14974    0                0.36             0.54               2   
14975    0                0.10             0.79               7   
14976    0                0.40             0.47               2   
14977    0                0.81             0.85               4   
14978    0                0.40             0.47               2   
14979    0                0.09             0.93               6   
14980    0                0.76             0.89               5   
14981    1                0.73             0.93               5   
14982    0                0.38             0.49               2   
14983    0                0.72             0.84               5   
14984    0                0.40             0.56               2   
14985    0                0.91             0.99               5   
14986    1                0.85             0.85               4   
14987    1                0.90             0.70               5   
14988    1                0.46             0.55               2   
14989    1                0.43             0.57               2   
14990    1                0.89             0.88               5   
14991    1                0.09             0.81               6   
14992    1                0.40             0.48               2   
14993    1                0.76             0.83               6   
14994    1                0.40             0.57               2   
14995    1                0.37             0.48               2   
14996    1                0.37             0.53      

In [154]:
y

array([1, 0, 0, ..., 1, 1, 1])

In [155]:
from sklearn.preprocessing import OneHotEncoder

In [156]:
oh=OneHotEncoder(categorical_features=[0])

In [157]:
x=oh.fit_transform(x).toarray()

In [158]:
x

array([[ 0.,  1., 29.],
       [ 1.,  0., 71.],
       [ 1.,  0.,  2.],
       ...,
       [ 0.,  1., 28.],
       [ 0.,  1.,  2.],
       [ 0.,  1., 28.]])

In [ ]:
#split the dataset to train and test